- name: Set up PostgreSQL credentials
  hosts: localhost
  tasks:
    - name: Load PostgreSQL credentials from vault
      ansible.builtin.include_vars:
        file: vault.yml
        name: db_creds

    - name: Create .env file for Docker
      ansible.builtin.copy:
        dest: .env
        content: |
          POSTGRES_USER={{ db_creds.postgres_user }}
          POSTGRES_PASSWORD={{ db_creds.postgres_password }}
          POSTGRES_DB={{ db_creds.postgres_db }}
          TOPIC_NAME={{ db_creds.topic_name }}
          PARTITIONS_COUNT={{ db_creds.partitions_count }}
        mode: '0644'