pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('big_data_lab_4')
        VAULT_CREDS=credentials('vault')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login'){
            steps {
                // withCredentials([usernamePassword(credentialsId: 'big_data_lab_1', passwordVariable: 'DOCKERHUB_CREDS_PSW', usernameVariable: 'DOCKERHUB_CREDS_USR')]){
                //bat 'chcp 65001 && echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                //bat 'chcp 65001 && echo %DOCKERHUB_CREDS_PSW% | docker login -u %DOCKERHUB_CREDS_USR% --password-stdin'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Pull image'){
            steps{
                sh '''
                        docker pull synphase/big_data_lab_4:latest
                '''
            }
        }

        stage('Create environment') {
            steps {
                sh 'curl https://raw.githubusercontent.com/NikitaSelin/big_data_lab_4/main/create_env.sh -o create_env.sh'
                sh 'curl https://raw.githubusercontent.com/NikitaSelin/big_data_lab_4/main/setup.yml -o setup.yml'
                sh 'curl https://raw.githubusercontent.com/NikitaSelin/big_data_lab_4/main/vault.yml -o vault.yml'
                sh 'bash create_env.sh'
            }
        }

        stage('Download docker-compose.yml') {
            steps {
                sh 'curl https://raw.githubusercontent.com/NikitaSelin/big_data_lab_4/main/docker-compose.yml -o docker-compose.yml'
            }
        }

        stage('Run container'){
            steps{
                sh 'docker compose up -d'
                sh 'sleep 40'
                sh 'docker compose logs'
            }
        }
	}

    post {
        always {
            sh 'docker stop big_data_lab_4 && docker remove big_data_lab_4 && docker logout'
        }
    }
}