pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('big_data_lab_3')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {

        stage('Login'){
            steps {
                // withCredentials([usernamePassword(credentialsId: 'big_data_lab_1', passwordVariable: 'DOCKERHUB_CREDS_PSW', usernameVariable: 'DOCKERHUB_CREDS_USR')]){
                //bat 'chcp 65001 && echo %DOCKER_REGISTRY_PWD% | docker login -u %DOCKER_REGISTRY_USER% --password-stdin'}
                //bat 'chcp 65001 && echo %DOCKERHUB_CREDS_PSW% | docker login -u %DOCKERHUB_CREDS_USR% --password-stdin'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Pull image'){
            steps{
                sh '''
                        docker pull synphase/big_data_lab_3:latest
                '''
            }
        }

        stage('Run container'){
            steps{
                sh '''
                        docker run --name big_data_lab_3 -p 80:5556 -d synphase/big_data_lab_3:latest
                '''
            }
        }
	}

    post {
        always {
            sh 'docker stop big_data_lab_3 && docker remove big_data_lab_3 && docker logout'
        }
    }
}